# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[("data/images/boom.png", "data/images"),
	("data/images/chest.png", "data/images"),
	("data/images/coin.png", "data/images"),
	("data/images/diamond.png", "data/images"),
	("data/images/floor.png", "data/images"),
	("data/images/flying_stone.png", "data/images"),
	("data/images/fon_level.png", "data/images"),
	("data/images/inventory_background.png", "data/images"),
	("data/images/jade.png", "data/images"),
	("data/images/mine.png", "data/images"),
	("data/images/player.png", "data/images"),
	("data/images/player2.png", "data/images"),
	("data/images/player2_left.png", "data/images"),
	("data/images/player2_right.png", "data/images"),
	("data/images/player2_up.png", "data/images"),
	("data/images/stick.png", "data/images"),
	("data/images/stone.png", "data/images"),
	("data/images/table.png", "data/images"),
	("data/images/table_broken.png", "data/images"),
	("data/images/vase.png", "data/images"),
	("data/images/wall.png", "data/images"),
	("data/levels/map.txt", "data/levels"),
	("data/levels/map1.txt", "data/levels"),
	("data/levels/map2.txt", "data/levels"),
	("data/sounds/alex_f.mp3", "data/sounds"),
	("data/sounds/contra_theme.mp3", "data/sounds"),
	("data/sounds/explosion.wav", "data/sounds"),
	("data/sounds/menu_theme.mp3", "data/sounds"),
	("data/sounds/misson_passed.wav", "data/sounds"),
	("data/sounds/pick.wav", "data/sounds"),
	("data/sounds/tree.mp3", "data/sounds"),
	("data/sounds/woo.wav", "data/sounds"),],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Picker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
	icon = "data/icon.ico"
)
